### ISSUE TITLE
Support for Tuya Cameras - Fuers 3MP IP Camera Tuya Smart Home Indoor WiFi Wireless Surveillance Camera Automatic Tracking

### ISSUE THREAD

**Issue by SimovicTV** [rospogrigio/localtuya#1595]
## The problem

NO integration
Support for Tuya Cameras

## Environment
- Localtuya version: V5.2.1
- Home Assistant Core version:
Core
2023.12.3
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2
- [x] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya 
- [] Was the device working with earlier versions of localtuya ? 
- [x] Are you using the Tuya/SmartLife App in parallel ?

I am interested in integration, I have a tuya camera:

[https://www.aliexpress.com/item/4000310818781.html?spm=a2g0o.order_list.order_list_main.677.24c018026XwjZF](Fuers 3MP IP Camera Tuya Smart Home Indoor WiFi Wireless Surveillance Camera Automatic Tracking)

{
  "result": [
    {
      "active_time": 1681987913,
      "category": "sp",
      "create_time": 1681987913,
      "custom_name": "Security Camera",
      "icon": "smart/icon/ay1549882947781AQ72q/4cf54949c34f9fe00e6d76b56a64d384.png",
      "id": "xxxxxxxxxxxxxxxxxxxxx",
      "ip": "178.220.250.11",
      "is_online": true,
      "lat": "44.8100",
      "local_key": "xxxxxxxxxxxxxxxxxxx",
      "lon": "20.5400",
      "model": "",
      "name": "Security Camera",
      "product_id": "ypw676a5epnojkbw",
      "product_name": "通天下 JS-K259 300W",
      "sub": false,
      "time_zone": "+02:00",
      "update_time": 1703433782,
      "uuid": "szjs2bb08a7f02fbeebe"
    }
  ],
  "success": true,
  "t": 1703436940486,
  "tid": "44c8b802a27d11eea8201ee4eefad948"
}

{
  "result": {
    "properties": [
      {
        "code": "basic_indicator",
        "custom_name": "",
        "dp_id": 101,
        "time": 1703034136078,
        "value": false
      },
      {
        "code": "basic_flip",
        "custom_name": "",
        "dp_id": 103,
        "time": 1703034136080,
        "value": true
      },
      {
        "code": "basic_osd",
        "custom_name": "",
        "dp_id": 104,
        "time": 1703034136081,
        "value": true
      },
      {
        "code": "basic_private",
        "custom_name": "",
        "dp_id": 105,
        "time": 1703413007912,
        "value": false
      },
      {
        "code": "motion_sensitivity",
        "custom_name": "",
        "dp_id": 106,
        "time": 1703034136527,
        "value": "2"
      },
      {
        "code": "basic_nightvision",
        "custom_name": "",
        "dp_id": 108,
        "time": 1703034136524,
        "value": "0"
      },
      {
        "code": "sd_storge",
        "custom_name": "",
        "dp_id": 109,
        "time": 1703413055379,
        "value": "15220736|15115264|105472"
      },
      {
        "code": "sd_status",
        "custom_name": "",
        "dp_id": 110,
        "time": 1703413054503,
        "value": 1
      },
      {
        "code": "sd_format",
        "custom_name": "",
        "dp_id": 111,
        "time": 1682616107791,
        "value": true
      },
      {
        "code": "movement_detect_pic",
        "custom_name": "",
        "dp_id": 115,
        "time": 1681987913969
      },
      {
        "code": "ptz_stop",
        "custom_name": "",
        "dp_id": 116,
        "time": 1703435179440,
        "value": true
      },
      {
        "code": "sd_format_state",
        "custom_name": "",
        "dp_id": 117,
        "time": 1703034139325,
        "value": 0
      },
      {
        "code": "ptz_control",
        "custom_name": "",
        "dp_id": 119,
        "time": 1703435178496,
        "value": "7"
      },
      {
        "code": "motion_switch",
        "custom_name": "",
        "dp_id": 134,
        "time": 1703034136526,
        "value": false
      },
      {
        "code": "record_switch",
        "custom_name": "",
        "dp_id": 150,
        "time": 1703034136831,
        "value": true
      },
      {
        "code": "record_mode",
        "custom_name": "",
        "dp_id": 151,
        "time": 1703034139325,
        "value": "1"
      },
      {
        "code": "motion_tracking",
        "custom_name": "",
        "dp_id": 161,
        "time": 1703034139325,
        "value": false
      },
      {
        "code": "alarm_message",
        "custom_name": "",
        "dp_id": 185,
        "time": 1681987913969
      },
      {
        "code": "initiative_message",
        "custom_name": "",
        "dp_id": 212,
        "time": 1682822086957,
        "value": "eyJ2IjoiNC4wIiwiYnVja2V0IjoidHktZXUtc3RvcmFnZTMwIiwiY21kIjoiaXBjX21vdGlvbiIsInR5cGUiOiJpbWFnZSIsIndpdGgiOiJyZXNvdXJjZSIsImFsYXJtIjp0cnVlLCJ0aW1lIjoxNjgyODIyMDg2LCJmaWxlcyI6W1siLzgzNGFlYi03MjEyODg1LXN6anMyYmIwOGE3ZjAyZmJlZWJlL3VuaWZ5LzE2ODI4MjIwODYuanBlZyIsImVkN2JlNjQxYTA0ZDQ5NjciXV19"
      }
    ]
  },
  "success": true,
  "t": 1703437333317,
  "tid": "2ef79747a27e11ee953c8ae539fb2c20"
}

Thanks in advance

**Comment by keteflips** [comment]
I have another of this cameras.

**Comment by lparakhin** [comment]
> I have another of this cameras.

+1, any progress?

**Comment by EgoLLC** [comment]
+1
